# Generated by Django 5.1.2 on 2025-11-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_instagram_user_telegram_user_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, help_text='Instagram username', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, help_text='Telegram username', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp username or phone number', max_length=100),
        ),
    ]
