# Generated by Django 4.2.7 on 2025-11-05 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translations', models.JSONField(default=dict, help_text='{"ru": "Название", "en": "Name", "kg": "Аталышы"}')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translations', models.JSONField(default=dict, help_text='{"ru": {"title": "...", "description": "..."}, ...}')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('negotiable', 'Negotiable')], default='fixed', max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('views_count', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('reviews_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
