# Generated by Django 4.2.7 on 2025-11-05 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['-created_at'], name='services_se_created_d8afb6_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', '-created_at'], name='services_se_categor_588a33_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['city', '-created_at'], name='services_se_city_6d946d_idx'),
        ),
    ]
