# Generated by Django 4.2.7 on 2025-11-05 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'slug'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='services.category'),
        ),
        migrations.AddField(
            model_name='service',
            name='additional_services',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='average_check',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Средний чек за вместимость', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Вместимость (количество человек)', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='service',
            name='event_duration',
            field=models.CharField(blank=True, help_text='Длительность мероприятия', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='experience_years',
            field=models.IntegerField(blank=True, help_text='Опыт работы (лет)', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина'), ('any', 'Не важно')], default='any', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость за час', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='services/logos/'),
        ),
        migrations.AddField(
            model_name='service',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='video1',
            field=models.FileField(blank=True, null=True, upload_to='services/videos/'),
        ),
        migrations.AddField(
            model_name='service',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='services/videos/'),
        ),
        migrations.AddField(
            model_name='service',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('negotiable', 'Negotiable'), ('hourly', 'Hourly Rate')], default='fixed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status', '-created_at'], name='services_se_status_1c274a_idx'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='services.service'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'service')},
        ),
    ]
