# Generated by Django 5.1.2 on 2025-11-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_favorite_alter_category_options_category_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='search_text',
            field=models.TextField(blank=True, help_text='Combined searchable text from titles and descriptions'),
        ),
    ]
