# Generated by Django 5.1.2 on 2025-11-15 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_search_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['search_text'], name='services_se_search__afecb7_idx'),
        ),
    ]
