# Generated by Django 5.1.2 on 2025-11-15 10:27

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, help_text='Upload an icon image (PNG, JPG, GIF, SVG, WebP). GIF files will be animated. Max size: 5MB.', null=True, upload_to='categories/icons/', validators=[services.models.validate_icon_file]),
        ),
    ]
