# Generated by Django 5.1.2 on 2025-11-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='additional_services',
        ),
        migrations.RemoveField(
            model_name='service',
            name='average_check',
        ),
        migrations.RemoveField(
            model_name='service',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='service',
            name='event_duration',
        ),
        migrations.RemoveField(
            model_name='service',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='service',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='service',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='service',
            name='logo',
        ),
        migrations.AddField(
            model_name='service',
            name='additional_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Additional fields specific to the category'),
        ),
        migrations.AddField(
            model_name='service',
            name='advance_order_days',
            field=models.IntegerField(blank=True, help_text='Advance order required (days)', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='cake_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cake weight in kg', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='character_type',
            field=models.CharField(blank=True, help_text='Type of characters/animations', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='cuisine_type',
            field=models.CharField(blank=True, help_text='Type of cuisine', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='custom_calculation',
            field=models.BooleanField(default=False, help_text='Custom price calculation available'),
        ),
        migrations.AddField(
            model_name='service',
            name='decor_available',
            field=models.BooleanField(default=False, help_text='Decor available'),
        ),
        migrations.AddField(
            model_name='service',
            name='decoration_available',
            field=models.BooleanField(default=False, help_text='Vehicle decoration available'),
        ),
        migrations.AddField(
            model_name='service',
            name='delivery_included',
            field=models.BooleanField(default=False, help_text='Delivery included'),
        ),
        migrations.AddField(
            model_name='service',
            name='delivery_time_days',
            field=models.IntegerField(blank=True, help_text='Delivery time in days', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='dress_code',
            field=models.CharField(blank=True, help_text='Dress code', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='driver_included',
            field=models.BooleanField(default=False, help_text='Driver included'),
        ),
        migrations.AddField(
            model_name='service',
            name='drone_available',
            field=models.BooleanField(default=False, help_text='Drone shooting available'),
        ),
        migrations.AddField(
            model_name='service',
            name='equipment_provided',
            field=models.BooleanField(default=False, help_text='Equipment provided'),
        ),
        migrations.AddField(
            model_name='service',
            name='equipment_type',
            field=models.CharField(blank=True, help_text='Type of equipment for rental', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='flavors_available',
            field=models.TextField(blank=True, help_text='Available flavors'),
        ),
        migrations.AddField(
            model_name='service',
            name='full_day_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Full day shooting price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='guard_count',
            field=models.IntegerField(blank=True, help_text='Number of guards', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='home_visit',
            field=models.BooleanField(default=False, help_text='Home visit available'),
        ),
        migrations.AddField(
            model_name='service',
            name='languages',
            field=models.CharField(blank=True, help_text='Languages spoken', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='license_number',
            field=models.CharField(blank=True, help_text='License number', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='lighting_type',
            field=models.CharField(blank=True, help_text='Type of lighting', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='love_story_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Love story shooting price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='menu_available',
            field=models.BooleanField(default=False, help_text='Menu available'),
        ),
        migrations.AddField(
            model_name='service',
            name='minimum_order',
            field=models.IntegerField(blank=True, help_text='Minimum order quantity', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='montage_included',
            field=models.BooleanField(default=False, help_text='Video montage included'),
        ),
        migrations.AddField(
            model_name='service',
            name='music_genre',
            field=models.CharField(blank=True, help_text='Music genre', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='parking_available',
            field=models.BooleanField(default=False, help_text='Parking available'),
        ),
        migrations.AddField(
            model_name='service',
            name='performance_type',
            field=models.CharField(blank=True, choices=[('live', 'Live'), ('dj', 'DJ'), ('backing_track', 'Backing Track')], default='live', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='performance_video',
            field=models.URLField(blank=True, help_text='Link to performance video'),
        ),
        migrations.AddField(
            model_name='service',
            name='portfolio_photos_count',
            field=models.IntegerField(blank=True, help_text='Number of photos in portfolio', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='projector_available',
            field=models.BooleanField(default=False, help_text='Projector available'),
        ),
        migrations.AddField(
            model_name='service',
            name='props_included',
            field=models.BooleanField(default=False, help_text='Props included'),
        ),
        migrations.AddField(
            model_name='service',
            name='rental_duration',
            field=models.CharField(blank=True, help_text='Rental duration (day, week, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rental price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='repertoire',
            field=models.TextField(blank=True, help_text='Repertoire description'),
        ),
        migrations.AddField(
            model_name='service',
            name='second_operator',
            field=models.BooleanField(default=False, help_text='Second operator available'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_duration',
            field=models.IntegerField(blank=True, help_text='Service duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(blank=True, choices=[('buffet', 'Buffet'), ('banquet', 'Banquet'), ('individual', 'Individual')], default='buffet', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='services_offered',
            field=models.TextField(blank=True, help_text='Services offered (arches, tables, photo zones, etc.)'),
        ),
        migrations.AddField(
            model_name='service',
            name='shooting_hour_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per shooting hour', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='shooting_style',
            field=models.CharField(blank=True, help_text='Shooting style (reportage, studio, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='show_duration',
            field=models.IntegerField(blank=True, help_text='Show duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='show_type',
            field=models.CharField(blank=True, help_text='Type of show/performance', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='sound_available',
            field=models.BooleanField(default=False, help_text='Sound system available'),
        ),
        migrations.AddField(
            model_name='service',
            name='sound_recording',
            field=models.BooleanField(default=False, help_text='Sound recording included'),
        ),
        migrations.AddField(
            model_name='service',
            name='sound_system',
            field=models.CharField(blank=True, help_text='Sound system type', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='staff_count',
            field=models.IntegerField(blank=True, help_text='Number of staff members', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='staff_included',
            field=models.BooleanField(default=False, help_text='Staff included'),
        ),
        migrations.AddField(
            model_name='service',
            name='stage_available',
            field=models.BooleanField(default=False, help_text='Stage available'),
        ),
        migrations.AddField(
            model_name='service',
            name='stage_requirements',
            field=models.TextField(blank=True, help_text='Stage requirements'),
        ),
        migrations.AddField(
            model_name='service',
            name='stage_setup',
            field=models.BooleanField(default=False, help_text='Stage setup included'),
        ),
        migrations.AddField(
            model_name='service',
            name='time_limit',
            field=models.CharField(blank=True, help_text='Time limit for performance', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='uniform_provided',
            field=models.BooleanField(default=False, help_text='Uniform provided'),
        ),
        migrations.AddField(
            model_name='service',
            name='vehicle_capacity',
            field=models.IntegerField(blank=True, help_text='Vehicle capacity', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='vehicle_type',
            field=models.CharField(blank=True, help_text='Type of vehicle', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='video_format',
            field=models.CharField(blank=True, choices=[('hd', 'HD'), ('4k', '4K'), ('full_hd', 'Full HD')], default='hd', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='video_presentation',
            field=models.URLField(blank=True, help_text='Link to video presentation'),
        ),
        migrations.AddField(
            model_name='service',
            name='wedding_decor_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average wedding decor price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='working_hours',
            field=models.CharField(blank=True, help_text='Working hours', max_length=100),
        ),
    ]
