# Generated by Django 5.1.2 on 2025-11-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_service_additional_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Venue capacity', null=True),
        ),
    ]
