# Generated by Django 5.1.2 on 2025-11-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_add_capacity_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='additional_services',
            field=models.TextField(blank=True, help_text='Additional services offered'),
        ),
        migrations.AddField(
            model_name='service',
            name='average_check',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average check', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='event_duration',
            field=models.IntegerField(blank=True, help_text='Event duration in hours', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='experience_years',
            field=models.IntegerField(blank=True, help_text='Years of experience', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина'), ('any', 'Не важно')], default='any', help_text='Gender preference', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate', max_digits=10, null=True),
        ),
    ]
