# Generated by Django 5.1.2 on 2025-11-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_add_common_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji icon for the category', max_length=10, null=True),
        ),
    ]
