# Generated by Django 5.1.2 on 2025-11-16 11:54

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, help_text='Icon image for the category', null=True, upload_to='categories/icons/', validators=[services.models.validate_icon_file]),
        ),
    ]
