# Generated by Django 5.1.2 on 2025-11-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='telegram',
            field=models.CharField(blank=True, help_text='Telegram username', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp username or phone number', max_length=100),
        ),
    ]
