# Generated by Django 5.1.2 on 2025-11-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_service_telegram_service_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='district',
        ),
    ]
