# Generated by Django 5.1.2 on 2025-11-19 05:32

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_remove_district_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Avatar image for the service', null=True, upload_to='services/avatars/', validators=[services.models.validate_icon_file]),
        ),
    ]
